### ISSUE TITLE
Tilting iPhone to the left gives upside down graph

### ISSUE THREAD

**Issue by electrokean** [mooshim/Mooshimeter-IOSApp#13]
Tilting the iPhone to the left shows the graph properly, but it quickly turns upside down
Tilting the iPhone to the right works fine, and with a quick swivel of the wrist you can turn the phone the other way the the graph will rotate properly and now stays the right way up.

Tested with Mooshimeter iOS App v1.03 (71) on iPhone 4S running iOS 8.1.3

**Comment by jwhong** [comment]
Fixed
