### ISSUE TITLE
App takes a long time to boot

### ISSUE THREAD

**Issue by jwhong** [mooshim/Mooshimeter-IOSApp#15]
Probably it's the firmware upgrade check

**Comment by electrokean** [comment]
That's what I thought it might be - I noticed it is quicker when on my home wireless vs. the office.
I'd suggest you display some kind of splash screen before starting the check.

**Comment by ianfixes** [comment]
The act of checking seems to block an important thread.  At least, it causes problems in UIAutomation.

```
2015-04-17 00:58:07.469 ScriptAgent[36829:3007] AX Lookup problem! 1102 com.apple.iphone.axserver:36827
2015-04-17 00:58:08.472 ScriptAgent[36829:3007] AX Lookup problem! 1102 com.apple.iphone.axserver:36827
```

To reproduce, connect to wifi but disconnect the wifi router from your modem.  Then try to use the app in Instruments.

**Comment by jwhong** [comment]
Moved firmware check to background
