### ISSUE TITLE
Make graph settings sticky

### ISSUE THREAD

**Issue by jwhong** [mooshim/Mooshimeter-IOSApp#21]

**Comment by alfishe** [comment]
Making graph stable and not jumping as hell - that needs to be a target. For now it reacts on every noise and random peaks. Scale selection needs to be filtered from with lo-pass filter and scale changes done using curve, not instantly. Then it might have both positive factors: be reasonably static to improve readability and adaptive at the same time.

To be honest - graph component should be much more sophisticated (at least in terms of rendering). Antialiasing is a must. Non-annoying scrolling/scaling animations - next

**Comment by jwhong** [comment]
I made graph settings sticky on the dev branch - they are cleared when the app is closed and restarted but persistent within a session.

Regarding general graphing upgrades - What phone do you use?  I do most of my testing now on an iPad mini and scrolling/scaling is pretty smooth.

Thanks again for your help

**Comment by alfishe** [comment]
Have iPhone5, iPhone 7 and iPad Air. It's not about graph render performance. It's about overall method how graph is plotted. It's not enough just to plot next measurement as a point, draw line from the previous measurement and immediately make whole graph re-scale on X axis or scroll.
Look at user experience in Fluke iOS app - https://youtu.be/6prvmKU6XbM?t=102
It's far from perfection but much less sluggish. And they don't use straight lines. Seems some interpolation and Bezier curves used and that provide totally different feeling.
I've read few recent comments to Mooshimeter on Amazon  - jumping graph is a real pain for users
