### ISSUE TITLE
MIN/MAX

### ISSUE THREAD

**Issue by jwhong** [mooshim/Mooshimeter-IOSApp#24]
Andreas: It would be nice to have a MIN/MAX function in DMM Mode, which holds the lowest and highest values during a measurement. There is enough space to display Min and Max with a small font below the actual value. And, maybe a button between ZERO and SOUND to enable/disable MIN/MAX (which resets also the MIN/MAX values when enabled again).

**Comment by alfishe** [comment]
Feature added but... you forgot to add MinMaxTracker.m/.h files to project (or just didn't commit project changes) =)

**Comment by jwhong** [comment]
Thanks Alfishe :)  I believe I've addressed this on the dev branch and will be releasing to beta shortly

**Comment by alfishe** [comment]
I'm re-creating Mooshimeter app functionality in Swift (mostly for self-education). That's why I'm so picky about every issue with build =)))

**Comment by jwhong** [comment]
That's awesome - please let me know how I can help.  I looked in to porting to swift a year ago but lost momentum because I think I hit some hitches making CorePlot work and it was a lot of work for not much payoff since I was the only one working on the app.  I looked at your profile and starred your project, can't wait to see how it develops.

**Comment by alfishe** [comment]
If you can share protocol details as high level diagrams - that will be awesome. I'm proficient both in Obj-C and Java but implementation differs a bit and last switching from separate BLE properties to streaming using just two properties had me to trash some of work. Hope that there will be no such drastic changes going forward.
Probably if you have some time - we can chat about mooshimeter software development stuff. You've created very elegant hardware, but end-user software for now cannot reveal even small fraction of it's capabilities.

**Comment by jwhong** [comment]
Sorry about the protocol change.  I don't plan on doing another change as drastic - the point of the new protocol is to be easily expandable without deep changes.  It's basically a serial port emulated over BLE.  I'll start writing about it here: https://moosh.im/wiki/index.php/Main_Page#Protocol_Documentation

I agree 100% regarding the hardware being more solid than the software.  This is my first iOS app and first Android app and it shows... I would love to chat about your ideas for the software and improvements.  Please email me at james@moosh.im and we can exchange some skype details or something.
