### ISSUE TITLE
Support landscape mode on iPad

### ISSUE THREAD

**Issue by joebowbeer** [mooshim/Mooshimeter-IOSApp#28]
The iOS app has an annoying glitch that causes it to appear broken when it is started in one orientation and then the orientation is changed:

[Current iPad line](https://moosh.im/f/topic/current-ipad-line/#post-15354)

```
I think what’s happening is actually not related to your screen resolution but a bug
in the startup in the app where it incorrectly locks in whatever orientation you had
when you started the app.
```

In addition to fixing this, it would be great to provide decent support for landscape mode.

**Comment by jwhong** [comment]
I think I've found the issue... it's an annoying change in autorotation behavior introduced in iOS8.  I've submitted a new build for testing, it's in beta now.  I will close this issue for now, if I failed to fix it we can reopen.  Thank you!
