### ISSUE TITLE
Looks like this product ist dead, right?

### ISSUE THREAD

**Issue by stelioskat** [mooshim/Mooshimeter-IOSApp#29]
The app is seriously outdated and makes the rather expensive multimeter not fun to use...

**Comment by gijsvanz** [comment]
Do you know an app that does work? I'm not able to use my mooshimeter (build 04-2015)

**Comment by stelioskat** [comment]
Only the original app. Some time ago it still worked, not sure about now, but has some serious issues. Pretty sad. I've given up on this project and will be using from now on only "serious" solutions instead.

**Comment by gijsvanz** [comment]
Oh... oke, pretty sad indeed. Thanks for the response.


Gijs van Zonneveld

telefoon +316 51358186
Randonneix
23430 Châtelus-le-Marcheix




Op wo 5 apr 2023 om 11:05 schreef Stelios Katsanevakis <
***@***.***>:
